<?php
// Подключение библиотеки для парсинга
include 'lib\simplehtmldom\simple_html_dom.php';


// Create a DOM object
$html = new simple_html_dom();

// Load HTML from a URL
$html->load_file('http://gmmyachting-datatransfer-v1.loc/responce-on-hurl.html');

//$ret = $html->find('div[class=box_content]');

// Find all images
foreach($html->find('.column4', 0) as $element)
       echo $element->plaintext . '<br>';

// echo $html->plaintext;

?>



<?php

// // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
// $ch = curl_init();
//
// curl_setopt($ch, CURLOPT_URL, "http://gmmyachting-datatransfer-v1.loc/responce-on-second-request.php");
// curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
//
// $result = curl_exec($ch);
// if (curl_errno($ch)) {
//     echo 'Error:' . curl_error($ch);
// }
// curl_close($ch);
//
// # Вывод данных на экран
// // print_r($result);
// echo $result;

?>
